### PR TITLE
added code to build with rkt

### PR DESCRIPTION
**Pull request by rbucker**
CoreOS comes preinstalled with rkt and git. It is my intention to put together a CI/CD system based on as few layers as possible and as little docker as possible. The tar.gz file did not work for me and so I started putting together an analog to build-docker called build-rkt which uses alpine 3.4.

### CODE REVIEW

**Comment by sanmai-NL** [comment]
What’s the status of this?

**Comment by dgonyeo** [comment]
This looks fine to me. If @rbucker is willing to fix the build conflict I'd be happy to merge it.

**Comment by dgonyeo** [comment]
Thanks!

**Comment by sanmai-NL** [comment]
@dgonyeo:
A note regarding this PR. I think the merged in README section
https://github.com/containers/build/tree/44d12bf74ef323f3e38ca75be42cf01bfa058549#building-acbuild-with-rkt right now isn't worded appropriately. It is a personal note taken verbatim from the PR. Agree?

**Comment by dgonyeo** [comment]
Huh yeah, I must have missed that. Any chance you'd be willing to fix it?

**Comment by sanmai-NL** [comment]
@dgonyeo: I think it's most appropriate if @rbucker fixes it.

**Comment by rbucker** [comment]
@sanmai-NL @dgonyeo I do not know what the offense is so you are welcome to create an issue and assign it to me and maybe I'll repair it if it's reasonable. You are also welcome to make any changes you like. I will not take offense.

**Comment by dgonyeo** [comment]
I just made a PR to fix this: https://github.com/containers/build/pull/323

**Pull request merged**
